In [42]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import tensorflow as tf
import matplotlib.pyplot as plt

In [43]:
df=pd.read_csv('D:/vs_code_dl/files/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [44]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [45]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0


In [46]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [47]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [48]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [50]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[0.05882353, 0.47738693, 0.49180328, ..., 0.3561848 , 0.07771136,
        0.01666667],
       [0.29411765, 0.52763819, 0.59016393, ..., 0.54992548, 0.03458582,
        0.11666667],
       [0.        , 0.67839196, 0.55737705, ..., 0.63040238, 0.12254483,
        0.05      ],
       ...,
       [0.58823529, 0.50753769, 0.70491803, ..., 0.67958271, 0.45175064,
        0.28333333],
       [0.        , 0.70854271, 0.        , ..., 0.6318927 , 0.05422716,
        0.13333333],
       [0.        , 0.6281407 , 0.78688525, ..., 0.33532042, 0.07856533,
        0.        ]], shape=(537, 8))

In [51]:
#model creation
from keras.models import Sequential
from keras.layers import Dense

In [52]:
ann=Sequential() #intialization
#input layer
ann.add(Dense(units=4,activation='relu'))
#hidden layer
ann.add(Dense(units=10,activation='relu'))
#hidden layer
ann.add(Dense(units=6,activation='relu'))

#op layer
ann.add(Dense(units=1,activation='sigmoid'))


In [53]:
#compile
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [54]:
ann.fit(x_train,y_train,epochs=100,batch_size=20)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3687 - loss: 0.7025
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6201 - loss: 0.6880
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6518 - loss: 0.6792
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6740
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6692
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6649
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6604
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6568
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6537
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6516
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6499
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy:

In [55]:
ann.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 479 (1.88 KB)

 Trainable params: 159 (636.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 320 (1.25 KB)

In [56]:
ann.evaluate(x_test,y_test)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7100 - loss: 0.5361  


[0.5361334681510925, 0.709956705570221]

In [57]:
x_train.shape

(537, 8)

In [58]:
y_pred=ann.predict(x_test)
y_pred

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step


array([[0.5994513 ],
       [0.08732904],
       [0.07446897],
       [0.395135  ],
       [0.7304278 ],
       [0.7871579 ],
       [0.04281316],
       [0.22737642],
       [0.6349019 ],
       [0.39064857],
       [0.3814539 ],
       [0.7572762 ],
       [0.33688846],
       [0.7305645 ],
       [0.11242682],
       [0.5191852 ],
       [0.1317941 ],
       [0.07897872],
       [0.2827849 ],
       [0.38504395],
       [0.5711275 ],
       [0.12910362],
       [0.62375844],
       [0.07355217],
       [0.6044345 ],
       [0.8192977 ],
       [0.11847597],
       [0.0636142 ],
       [0.12284227],
       [0.36094707],
       [0.7434968 ],
       [0.38593695],
       [0.66363287],
       [0.49097866],
       [0.85398036],
       [0.7416093 ],
       [0.7851386 ],
       [0.5616275 ],
       [0.39424852],
       [0.51940656],
       [0.10502678],
       [0.2112273 ],
       [0.65171456],
       [0.4741229 ],
       [0.05313681],
       [0.583851  ],
       [0.8244033 ],
       [0.177

In [59]:
y_pred=ann.predict(scaler.transform([[5,130,80,32,0,31.2,0.672,45]]))
y_pred


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[0.7600889]], dtype=float32)

In [60]:
if y_pred>0.5:
    print("Diabetic Patient")
else:
    print("Not a Diabetic Patient")

Diabetic Patient
